export const GET_DC_SUPERHEROES_REQUEST = 'GET_DC_SUPERHEROES_REQUEST';
export const GET_DC_SUPERHEROES_REQUEST_SUCCESS =
  'GET_DC_SUPERHEROES_REQUEST_SUCCESS';
export const GET_DC_SUPERHEROES_REQUEST_FAILED =
  'GET_DC_SUPERHEROES_REQUEST_FAILED';
